services:
  
  db:
    image: postgres
    container_name: db-blog
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/dbdata
    environment:
      - POSTGRES_PASSWORD=1804
      - POSTGRES_DB=blog-api

  db-test:
    image: postgres
    container_name: db-blog-test
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=1804
      - POSTGRES_DB=blog-api

  app:
    image: caioprog/blog-nest-api:SNAPSHOT-0.0.1
    container_name: blog-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "npx typeorm migration:run -d dist/src/database/orm.migrations.config.js && npm run start:prod"
  
